### ISSUE TITLE
Git 2.6.2 fails to build on AIX

### ISSUE THREAD

**Issue by curiositycasualty** [chef/omnibus-toolchain#21]
Thus the reversion (for now).

The original intent was to move to what's pulled in via the omnibus cookbook: https://github.com/chef/omnibus-toolchain/pull/19
This it the root of my work:
- https://github.com/chef/omnibus-toolchain/pull/20
- https://github.com/chef/omnibus-software/pull/533

/cc @chef/omnibus-maintainers @chef/engineering-services

**Comment by scotthain** [comment]
Updated to 2.7 in release 1.1.6!
