### ISSUE TITLE
Debian 9.1 dpkg-deb incompatible with omnibus-toolchain tar (1.28 vs. 1.29)

### ISSUE THREAD

**Issue by mattray** [chef/omnibus-toolchain#73]
Built latest omnibus-toolchain, using to build Chef 13.3.42 from source on ARM for Debian 9.1. It fails at the following point:

          [Packager::DEB] D | 2017-08-21T11:00:04+10:00 | SCRIPT FILE:  /tmp/chef20170821-12869-dvyw1e/DEBIAN/postrm
          [Packager::DEB] D | 2017-08-21T11:00:30+10:00 | Using vendored resource `md5sums.erb'
          [Packager::DEB] I | 2017-08-21T11:00:30+10:00 | Rendering `/opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/bundler/gems/omnibus-5169733866be/resources/deb/md5sums.erb' to `/tmp/chef20170821-12869-dvyw1e/DEBIAN/md5sums'
          [Packager::DEB] I | 2017-08-21T11:00:30+10:00 | Creating .deb file
          [Packager::DEB] I | 2017-08-21T11:00:31+10:00 | Packaging time: 142.8715s
The following shell command exited with status 2:

    $ fakeroot dpkg-deb -z1 -Zxz -D --build /tmp/chef20170821-12869-dvyw1e chef_13.3.42+20170820223355-1_armhf.deb

Output:

    dpkg-deb: building package 'chef' in 'chef_13.3.42+20170820223355-1_armhf.deb'.

Error:

    tar: unrecognized option '--clamp-mtime'
Try 'tar --help' or 'tar --usage' for more information.
dpkg-deb: error: subprocess tar -cf returned error exit status 64

/opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/bundler/gems/omnibus-5169733866be/lib/omnibus/util.rb:139:in `rescue in shellout!'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/bundler/gems/omnibus-5169733866be/lib/omnibus/util.rb:135:in `shellout!'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/bundler/gems/omnibus-5169733866be/lib/omnibus/packagers/deb.rb:374:in `block in create_deb_file'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/bundler/gems/omnibus-5169733866be/lib/omnibus/packagers/deb.rb:373:in `chdir'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/bundler/gems/omnibus-5169733866be/lib/omnibus/packagers/deb.rb:373:in `create_deb_file'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/bundler/gems/omnibus-5169733866be/lib/omnibus/packagers/deb.rb:62:in `block in <class:DEB>'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/bundler/gems/omnibus-5169733866be/lib/omnibus/packagers/base.rb:147:in `instance_eval'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/bundler/gems/omnibus-5169733866be/lib/omnibus/packagers/base.rb:147:in `block in run!'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/bundler/gems/omnibus-5169733866be/lib/omnibus/instrumentation.rb:23:in `measure'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/bundler/gems/omnibus-5169733866be/lib/omnibus/packagers/base.rb:144:in `run!'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/bundler/gems/omnibus-5169733866be/lib/omnibus/project.rb:1145:in `block in package_me'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/bundler/gems/omnibus-5169733866be/lib/omnibus/project.rb:1138:in `each'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/bundler/gems/omnibus-5169733866be/lib/omnibus/project.rb:1138:in `package_me'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/bundler/gems/omnibus-5169733866be/lib/omnibus/project.rb:1087:in `build'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/bundler/gems/omnibus-5169733866be/lib/omnibus/cli.rb:89:in `build'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/bundler/gems/omnibus-5169733866be/lib/omnibus/cli/base.rb:33:in `dispatch'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/bundler/gems/omnibus-5169733866be/lib/omnibus/cli.rb:42:in `execute!'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/bundler/gems/omnibus-5169733866be/bin/omnibus:16:in `<top (required)>'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/bin/omnibus:22:in `load'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/bin/omnibus:22:in `<top (required)>'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
  /opt/omnibus-toolchain/bin/bundle:22:in `load'
  /opt/omnibus-toolchain/bin/bundle:22:in `<main>'
omnibus@cubert:~/chef-13.3.42/omnibus$ which tar
/opt/omnibus-toolchain/bin/tar

Remove the /opt/omnibus-toolchain/bin/tar from the path and the build succeeds.
```
$ /opt/omnibus-toolchain/bin/tar/opt/omnibus-toolchain/bin/tar --version
tar (GNU tar) 1.28
$ /bin/tar --version
tar (GNU tar) 1.29
```

**Comment by scotthain** [comment]
Unfortunately gtar 1.29 compilation fails on AIX, macOS, ppc64le, s390x and a few others in our build pipeline and will require some tweaking/patches. I expect we will pick these up when when/if we move to Debian 9.

**Comment by repeatedly** [comment]
Do we have a workaround for this issue?

**Comment by legal90** [comment]
@repeatedly As a workaround, you can just remove `/opt/omnibus-toolchain/bin/tar` manually, so omnibus will use the next `tar` executable available by PATH, which is usually `/bin/tar`.
It works for me on Debian 9.4 x86_64.

**Comment by repeatedly** [comment]
@legal90 Thanks for the info!
I updated my Vagrantfile to remove omnibus-toolchain's tar and it worked.

```
      if platform.start_with?('debian-9')
        c.vm.provision :shell, :privileged => true, :inline => <<-REMOVE_TAR
        rm /opt/omnibus-toolchain/bin/tar
        rm /opt/omnibus-toolchain/bin/gtar
        rm /opt/omnibus-toolchain/embedded/bin/tar
      REMOVE_TAR
      end
```

**Comment by legal90** [comment]
> Unfortunately gtar 1.29 compilation fails on AIX, macOS, ppc64le, s390x and a few others in our build pipeline and will require some tweaking/patches.

@scotthain Did you tried gtar 1.30 ? It was released in December 2017:
https://savannah.gnu.org/forum/forum.php?forum_id=9027

**Comment by scotthain** [comment]
@legal90 I'll add a card to our board to test that out - thanks for the heads up!

**Comment by mattray** [comment]
Rebuilt Debian toolchain, this is still an issue

**Comment by alexanderBendo** [comment]
It also fails in Ubuntu 18.04 (bionic)

**Comment by jaymalasinha** [comment]
@mattray @alexanderBendo are you running Chef 13 on your builder?  We are running Chef 14 on our builders and haven't seen the issue yet.

**Comment by mattray** [comment]
I'm on Chef 14.4 on ARM.

**Comment by alexanderBendo** [comment]
@jaymalasinha Yes, I'm using Chef 13

**Comment by ramereth** [comment]
Any update on seeing if the latest gtar release works on AIX now so we can get this bumped?

**Comment by tas50** [comment]
One of the gtar things we need to fix for this:

https://github.com/chef/omnibus-software/pull/1059

**Comment by mattray** [comment]
I can verify this works with 32-bit ARM Raspbian and Debian builds now.
